version: '3'
services:
  mapfish-print-v2:
    build:
      context: mapfish-print-v2/
      args:
        - MAPFISH2_VERSION=2.1.5
    ports:
      - 18082:8080
    volumes:
      - ./mapfish-print-v2/print-config/config.yaml:/opt/apache-tomcat-8.5.37/webapps/print/config.yaml:Z
  mapfish-print-v3:
    build:
      context: mapfish-print-v3/
    ports:
      - 18083:8080
    volumes:
      - ./mapfish-print-v3/print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:Z
